* My Emacs configuration file
  I decided to use literate programming for my configuration file, mainly spired by [[http://sachachua.com/][Sacha Chua]], since it's easier to read an understand what's going on in my conf and what kind of packages I'm using and I'm trying to learn.
* Basic configuration

First I have to add ~/.emacs.d to the load path in order to easily load additional .el files 
#+begin_src emacs-lisp :tangle yes
(add-to-list 'load-path user-emacs-directory) ;; ~/.emacs.d
#+end_src

I also gatta check if the current environment is a mac computer.
#+begin_src emacs-lisp :tangle yes
(setq is-mac (equal system-type 'darwin))
#+end_src
* Helper functions

This is a set of helper functions for an easier configuration.

#+begin_src emacs-lisp :tangle yes
(defun add-to-path (dir)
"Adds dir to the PATH environment variable"
(setenv "PATH" (concat (format "%s:" dir) (getenv "PATH"))))
#+end_src
* Local environment setup
#+begin_src emacs-lisp :tangle yes
(add-to-path "~/.cask/bin")
#+end_src


* Cask
I'm using cask for managing my installed packages now :)
#+BEGIN_SRC emacs-lisp :tangle yes
(require 'cask "~/.cask/cask.el")
(cask-initialize)
#+END_SRC

* Yasnippet
#+begin_src emacs-lisp :tangle yes
(yas-global-mode)
#+end_src

* Projectile
  In order to have projectile enabled globally I have to call it's gobal-mode function.
#+BEGIN_SRC emacs-lisp :tangle yes
(projectile-global-mode)
#+END_SRC
* TODOS
** TODO Check how to make the lines not to be hidden when the screen is thinner than text. 
** TODO Check use-package to better manage packages
** TODO Check cask to better manage packages
