(source gnu)
(source melpa)

;; (depends-on "dash")
(depends-on "helm")
(depends-on "helm-open-github")
;(depends-on "guide-key")
(depends-on "js2-mode")
(depends-on "magit")
(depends-on "smartparens")
(depends-on "helm-css-scss")
(depends-on "helm-spotify")
(depends-on "bind-key")
(depends-on "org-pomodoro")
(depends-on "ace-jump-mode")
(depends-on "auto-complete")
(depends-on "fringe-helper")
(depends-on "git-gutter-fringe+")
(depends-on "rainbow-mode")
(depends-on "markdown-mode")
(depends-on "go-mode")
(depends-on "go-eldoc")
(depends-on "go-autocomplete")
(depends-on "ace-window")
(depends-on "expand-region")
(depends-on "elpy")
(depends-on "virtualenvwrapper")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "smex")

(depends-on "zencoding-mode")
(depends-on "rainbow-delimiters")

(depends-on "yasnippet")

(depends-on "seti-theme")

(depends-on "erc-hl-nicks")
